# Make sure we’re using the latest Homebrew
update
# Upgrade any already-installed formulae
upgrade
# Version Control
install git

tap homebrew/versions

# Remove outdated versions from the cellar
cleanup